package br.com.siscon.view;

import java.util.ArrayList;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import br.com.siscon.util.Datas;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import br.com.siscon.model.ClienteModel;
import br.com.siscon.model.ProdutoModel;
import br.com.siscon.model.ProdutosVendasProdutosModel;
import br.com.siscon.model.VendasClientesModel;
import br.com.siscon.model.VendasModel;
import br.com.siscon.model.VendasProdutosModel;
import br.com.siscon.service.ClienteService;
import br.com.siscon.service.ProdutoService;
import br.com.siscon.service.ProdutosVendasProdutosService;
import br.com.siscon.service.VendasClientesService;
import br.com.siscon.service.VendasProdutosService;
import br.com.siscon.service.VendasService;

/**
 *
 * @author joseluiz
 */
public class VendasView extends javax.swing.JInternalFrame {

    ClienteModel clienteModel = new ClienteModel();
    ClienteService clienteService = new ClienteService();
    ArrayList<ClienteModel> listaClienteModel = new ArrayList<>();

    ProdutoModel produtoModel = new ProdutoModel();
    ProdutoService produtoService = new ProdutoService();
    ArrayList<ProdutoModel> listaProdutoModel = new ArrayList<>();

    VendasClientesModel vendasClientesModel = new VendasClientesModel();
    VendasClientesService vendasClienteService = new VendasClientesService();
    ArrayList<VendasClientesModel> listaVendasCliente = new ArrayList<>();

    VendasModel vendasModel = new VendasModel();
    VendasService vendasService = new VendasService();
    ArrayList<VendasModel> listaModelVendas = new ArrayList<>();

    VendasProdutosModel vendasProdutoModel = new VendasProdutosModel();
    VendasProdutosService vendasProdutoService = new VendasProdutosService();
    ArrayList<VendasProdutosModel> listaVendasProdutoModel = new ArrayList<>();

    ProdutosVendasProdutosModel produtosVendasProdutosModel = new ProdutosVendasProdutosModel();
    ProdutosVendasProdutosService produtosVendasProdutosService = new ProdutosVendasProdutosService();
    ArrayList<ProdutosVendasProdutosModel> listaProdutosVendasProdutosModel = new ArrayList<>();

    Datas mascarasDatas = new Datas();
    String alterarSalvar;

    /**
     * Creates new form Vendas
     */
    public VendasView() {
        initComponents();
        listarClientes();
        listarProdutos();
        carregarVendas();
        preencherCodigoCliente();
        preencherCodigoProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jtfCodCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfNumeroVenda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfCodProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfQuantidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jbAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProdutosVendas = new javax.swing.JTable();
        jbCancelar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jtfValorTotal = new javax.swing.JTextField();
        jtfDesconto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbRemoverProdutos = new javax.swing.JButton();
        jcbNomeCliente = new componentes.UJComboBox();
        jcbNomeProduto = new componentes.UJComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jtfPesquisa = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtVendas = new javax.swing.JTable();
        jbExcluir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();

        setClosable(true);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(47, 79, 79));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtfCodCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfCodCliente.setEnabled(false);
        jtfCodCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodClienteFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Código Cli.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome do Cliente:");

        jtfNumeroVenda.setEditable(false);
        jtfNumeroVenda.setBackground(new java.awt.Color(153, 255, 204));
        jtfNumeroVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Número da Venda:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cód. Pro.");

        jtfCodProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfCodProduto.setEnabled(false);
        jtfCodProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodProdutoFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nome Produto:");

        jtfQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfQuantidade.setEnabled(false);
        jtfQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfQuantidadeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantidade:");

        jbAdicionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/siscon/imagens/Actions18x18/novo/icons8-mais-24.png"))); // NOI18N
        jbAdicionar.setText("Adicionar");
        jbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarActionPerformed(evt);
            }
        });

        jtProdutosVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtProdutosVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Prod.", "Descrição", "Quant.", "Unitário(R$)", "Total(R$)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtProdutosVendas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtProdutosVendas);

        jbCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscon/imagens/buttons/icons8-cancelar-2-24.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setToolTipText("Cancelar Venda");
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscon/imagens/buttons/icons8-adicionar-arquivo-24.png"))); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.setToolTipText("Nova Venda");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscon/imagens/buttons/icons8-salvar-24.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setToolTipText("Salvar Venda");
        jbSalvar.setEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jtfValorTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfValorTotal.setEnabled(false);

        jtfDesconto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfDesconto.setEnabled(false);
        jtfDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDescontoFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(208, 240, 214));
        jLabel7.setText("Valor Total:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(208, 240, 214));
        jLabel8.setText("Desconto:");

        jbRemoverProdutos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbRemoverProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscon/imagens/buttons/icons8-lixo-24.png"))); // NOI18N
        jbRemoverProdutos.setText("Remover Produtos");
        jbRemoverProdutos.setToolTipText("Remover Produtos");
        jbRemoverProdutos.setEnabled(false);
        jbRemoverProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverProdutosActionPerformed(evt);
            }
        });

        jcbNomeCliente.setEnabled(false);
        jcbNomeCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbNomeCliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcbNomeClientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jcbNomeProduto.setEnabled(false);
        jcbNomeProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbNomeProduto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcbNomeProdutoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtfCodProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addComponent(jtfCodCliente)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfQuantidade))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(219, 219, 219)
                                        .addComponent(jLabel6)))
                                .addGap(0, 79, Short.MAX_VALUE))
                            .addComponent(jcbNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfNumeroVenda)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbRemoverProdutos)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(31, 31, 31))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbSalvar))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumeroVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAdicionar)
                    .addComponent(jcbNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbNovo)
                    .addComponent(jbSalvar)
                    .addComponent(jbRemoverProdutos))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jPanel2.setBackground(new java.awt.Color(47, 79, 79));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pesquisa:");

        jtfPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jbPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscon/imagens/buttons/icons8-pesquisar-filled-24.png"))); // NOI18N
        jbPesquisar.setText("Pesquisar");
        jbPesquisar.setToolTipText("Pesquisar Venda");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jtVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome Cliente", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVendas.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtVendas);

        jbExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscon/imagens/buttons/icons8-lixo-24.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setToolTipText("Excluir Venda");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siscon/imagens/buttons/icons8-crie-um-novo-24.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.setToolTipText("Alterar Venda");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbAlterar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfPesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(jbPesquisar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterar)
                    .addComponent(jbExcluir))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Consultar/Excluir/Alterar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCodClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodClienteFocusLost
        // TODO add your handling code here:
        clienteModel = clienteService.getClienteDAO(Integer.parseInt(jtfCodCliente.getText()));
        jcbNomeCliente.setSelectedItem(clienteModel.getCliNome());
    }//GEN-LAST:event_jtfCodClienteFocusLost

    private void jtfCodProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodProdutoFocusLost
        // TODO add your handling code here:
        produtoModel = produtoService.retornarProdutoDAO(jtfCodProduto.getText());
        jcbNomeProduto.setSelectedItem(produtoModel.getProDescricao());
    }//GEN-LAST:event_jtfCodProdutoFocusLost

    private void jtfQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfQuantidadeActionPerformed

    private void jbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarActionPerformed
        if (jtfQuantidade.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Você deve preencher todos os campos!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            produtoModel = produtoService.retornarProdutoDAO(jtfCodProduto.getText());
            //adiciona uma linha na tabela
            DefaultTableModel modelo = (DefaultTableModel) jtProdutosVendas.getModel();
            int cont = 0;
            double quantidade = 0;
            quantidade = Double.parseDouble(jtfQuantidade.getText());
            for (int i = 0; i < cont; i++) {
                modelo.setNumRows(0);
            }
            modelo.addRow(new Object[]{
                produtoModel.getProCodigoProduto(),
                produtoModel.getProDescricao(),
                jtfQuantidade.getText(),
                produtoModel.getProValorUnitario(),
                quantidade * produtoModel.getProValorUnitario()
            });
            somarValorTotalProduto();
            //  jtfQuantidade.setText(""); //talvez seja usado, serve para limpar o campo quantidade depois de adicionar um produto.
        }
    }//GEN-LAST:event_jbAdicionarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        limparFormulario();
        habilitarDesabilitarCampos(false);
        jbSalvar.setText("Salvar");
        jbNovo.setEnabled(true);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        // TODO add your handling code here:
        alterarSalvar = "salvar";
        habilitarDesabilitarCampos(true);
        jbNovo.setEnabled(false);
        jbSalvar.setText("Salvar");
        limparFormulario();
        preencherCodigoCliente();
        preencherCodigoProduto();
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // TODO add your handling code here:
        int codigoVenda = 0;
        double desconto = 0;
        int codigoProduto = 0;
        int quantidade = 0;
        listaVendasProdutoModel = new ArrayList<>();
        if (jtfDesconto.getText().equals("")) {
            desconto = 0;
        } else {
            desconto = Double.parseDouble(jtfDesconto.getText());
        }
        if (!jtfNumeroVenda.getText().equals("")) {
            vendasModel.setIdVenda(Integer.parseInt(jtfNumeroVenda.getText()));
        }
        vendasModel.setCliente(Integer.parseInt(jtfCodCliente.getText()));
        try {
            DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyy");
            LocalDateTime timepoint = LocalDateTime.now();
            vendasModel.setVenDataVenda(timepoint.format(fmt));
        } catch (Exception ex) {
            Logger.getLogger(VendasView.class.getName()).log(Level.SEVERE, null, ex);
        }
        vendasModel.setVenValorLiquido(Double.parseDouble(jtfValorTotal.getText()));
        vendasModel.setVenValorBruto(Double.parseDouble(jtfValorTotal.getText()) + desconto);
        vendasModel.setVenDesconto(desconto);

        codigoVenda = vendasService.salvarVendasDAO(vendasModel);
        if (codigoVenda > 0) {
            JOptionPane.showMessageDialog(this, "Venda salva com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao salvar a venda!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        int cont = jtProdutosVendas.getRowCount();
        for (int i = 0; i < cont; i++) {
            produtoModel = new ProdutoModel();
            vendasProdutoModel = new VendasProdutosModel();
            codigoProduto = (int) jtProdutosVendas.getValueAt(i, 0);
            //vendas
            vendasProdutoModel.setProduto(codigoProduto);
            vendasProdutoModel.setVendas(codigoVenda);
            vendasProdutoModel.setVendasProValor((double) jtProdutosVendas.getValueAt(i, 3));
            vendasProdutoModel.setVenProQuantidade(Integer.parseInt(jtProdutosVendas.getValueAt(i, 2).toString()));
            //produto
            produtoModel.setProCodigoProduto(codigoProduto);
            produtoModel.setProQuantidadeEstoque(produtoService.retornarProdutoDAO(String.valueOf(codigoProduto)).getProQuantidadeEstoque()
                    - Integer.parseInt(jtProdutosVendas.getValueAt(i, 2).toString()));
            listaVendasProdutoModel.add(vendasProdutoModel);
            listaProdutoModel.add(produtoModel);
        }
        //salvar os produtos da venda
        if (vendasProdutoService.salvarVendasProdutosDAO(listaVendasProdutoModel)) {
            // alterar estoque de produtos
            produtoService.alterarEstoqueProdutosDAO(listaProdutoModel);
            //JOptionPane.showMessageDialog(this, "Produtos da venda salvo com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
            carregarVendas();
            limparFormulario();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao salvar os produtos da venda!", "Erro", JOptionPane.ERROR_MESSAGE);
        }

        /*  if (alterarSalvar.equals("salvar")) {
            codigoVenda = vendasService.salvarVendasController(vendasModel);
            if (codigoVenda > 0) {
                JOptionPane.showMessageDialog(this, "Venda salva com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar a venda!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            int cont = jtProdutosVendas.getRowCount();
            for (int i = 0; i < cont; i++) {
                produtoModel = new ModelProdutos();
                vendasProdutoModel = new ModelVendasProdutos();
                codigoProduto = (int) jtProdutosVendas.getValueAt(i, 0);
                vendasProdutoModel.setProduto(codigoProduto);
                vendasProdutoModel.setVendas(codigoVenda);
                vendasProdutoModel.setVendasProValor((double) jtProdutosVendas.getValueAt(i, 3));
                vendasProdutoModel.setVenProQuantidade(Integer.parseInt(jtProdutosVendas.getValueAt(i, 2).toString()));
                //produto
                produtoModel.setIdProduto(codigoProduto);
                produtoModel.setProEstoque(produtoService.retornarProdutoController(codigoProduto).getProEstoque()
                    - Integer.parseInt(jtProdutosVendas.getValueAt(i, 2).toString()));
                listaVendasProdutoModel.add(vendasProdutoModel);
                listaProdutoModel.add(produtoModel);
            }
            //salvar os produtos da venda
            if (vendasProdutoService.salvarVendasProdutosController(listaVendasProdutoModel)) {
                // alterar estoque de produtos
                produtoService.alterarEstoqueProdutosController(listaProdutoModel);
                //                JOptionPane.showMessageDialog(this, "Produtos da venda salvo com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
                carregarVendas();
                limparFormulario();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar os produtos da venda!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else { //alterar a venda
            //[INICIO] RETORNAR PARA O ESTOQUE E EXCLUI DA VENDA
            int linha = jtVendas.getSelectedRow();
            codigoVenda = (int) jtVendas.getValueAt(linha, 0);

            listaProdutosVendasProdutosModel = produtosVendasProdutosService.getListaProdutosVendasProdutosDAOController(codigoVenda);
            for (int i = 0; i < listaProdutosVendasProdutosModel.size(); i++) {
                produtoModel = new ModelProdutos();
                vendasModel = new ModelVendas();
                vendasProdutoModel = new ModelVendasProdutos();
                produtoModel.setIdProduto(listaProdutosVendasProdutosModel.get(i).getModelProdutos().getIdProduto());
                produtoModel.setProEstoque((listaProdutosVendasProdutosModel.get(i).getModelProdutos().getProEstoque()
                    + listaProdutosVendasProdutosModel.get(i).getModelVendasProdutos().getVenProQuantidade()));
            listaProdutoModel.add(produtoModel);
        }
        if (produtoService.alterarEstoqueProdutosController(listaProdutoModel)) {
            if (vendasProdutoService.excluirVendasProdutosController(codigoVenda)) {
                //                    JOptionPane.showMessageDialog(this, "Venda excluida com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
                limparFormulario();
                carregarVendas();
                jbSalvar.setText("Salvar");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir a venda", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir a venda", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        //[FIM] RETORNAR PARA O ESTOQUE E EXCLUI DA VENDA
        }
        if (vendasService.atualizarVendasController(vendasModel)) {
            JOptionPane.showMessageDialog(this, "Venda alterada com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar a venda!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        codigoVenda = vendasService.salvarVendasController(vendasModel);
        if (codigoVenda > 0) {
            //            JOptionPane.showMessageDialog(this, "Venda salva com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao salvar a venda!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        //ADICIONAR PRODUTOS NA LISTA PARA SALVAR
        int cont = jtProdutosVendas.getRowCount();
        for (int i = 0; i < cont; i++) {
            produtoModel = new ModelProdutos();
            vendasProdutoModel = new ModelVendasProdutos();
            codigoProduto = (int) jtProdutosVendas.getValueAt(i, 0);
            vendasProdutoModel = new ModelVendasProdutos();
            produtoModel = new ModelProdutos();
            vendasProdutoModel.setProduto(codigoProduto);
            vendasProdutoModel.setVendas(codigoVenda);
            vendasProdutoModel.setVendasProValor((double) jtProdutosVendas.getValueAt(i, 3));
            vendasProdutoModel.setVenProQuantidade(Integer.parseInt(jtProdutosVendas.getValueAt(i, 2).toString()));

            //produto
            produtoModel.setIdProduto(codigoProduto);
            produtoModel.setProEstoque(produtoService.retornarProdutoController(codigoProduto).getProEstoque()
                - Integer.parseInt(jtProdutosVendas.getValueAt(i, 2).toString()));
            listaVendasProdutoModel.add(vendasProdutoModel);
            listaProdutoModel.add(produtoModel);
        }
        //SALVAR OS PRODUTOS DA VENDA
        if (vendasProdutoService.salvarVendasProdutosController(listaVendasProdutoModel)) {
            produtoService.alterarEstoqueProdutosController(listaProdutoModel);
            // JOptionPane.showMessageDialog(this, "Produtos da venda salvo com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
            limparFormulario();
            this.carregarVendas();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao salvar os produtos da venda!", "Erro", JOptionPane.ERROR_MESSAGE);
        }*/
        jbNovo.setEnabled(true);
        habilitarDesabilitarCampos(false);
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jtfDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDescontoFocusLost
        // TODO add your handling code here:
        somarValorTotalProduto();
    }//GEN-LAST:event_jtfDescontoFocusLost

    private void jbRemoverProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverProdutosActionPerformed
        // TODO add your handling code here:
        int linha = jtProdutosVendas.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) jtProdutosVendas.getModel();
        modelo.removeRow(linha);
        somarValorTotalProduto();
    }//GEN-LAST:event_jbRemoverProdutosActionPerformed

    private void jcbNomeClientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcbNomeClientePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (jcbNomeCliente.isVisible()) {
            preencherCodigoCliente();
        }
    }//GEN-LAST:event_jcbNomeClientePopupMenuWillBecomeInvisible

    private void jcbNomeProdutoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcbNomeProdutoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (jcbNomeProduto.isPopupVisible()) {
            preencherCodigoProduto();
        }
    }//GEN-LAST:event_jcbNomeProdutoPopupMenuWillBecomeInvisible

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) this.jtVendas.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.jtVendas.setRowSorter(classificador);
        String texto = jtfPesquisa.getText();
        classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:

        int linha = jtVendas.getSelectedRow();
        int codigoVenda = (int) jtVendas.getValueAt(linha, 0);

        listaProdutosVendasProdutosModel = produtosVendasProdutosService.getListaProdutosVendasProdutosDAO(codigoVenda);
        for (int i = 0; i < listaProdutosVendasProdutosModel.size(); i++) {
            produtoModel = new ProdutoModel();
            vendasModel = new VendasModel();
            vendasProdutoModel = new VendasProdutosModel();
            produtoModel.setProCodigoProduto(listaProdutosVendasProdutosModel.get(i).getModelProdutos().getProCodigoProduto());
            produtoModel.setProQuantidadeEstoque((listaProdutosVendasProdutosModel.get(i).getModelProdutos().getProQuantidadeEstoque()
                    + listaProdutosVendasProdutosModel.get(i).getModelVendasProdutos().getVenProQuantidade()));
            listaProdutoModel.add(produtoModel);
        }
        if (produtoService.alterarEstoqueProdutosDAO(listaProdutoModel)) {
            vendasProdutoService.excluirVendasProdutosDAO(codigoVenda);
            if (vendasService.excluirVendasDAO(codigoVenda)) {
                JOptionPane.showMessageDialog(this, "Venda excluida com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
                carregarVendas();
                jbSalvar.setText("Salvar");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir a venda", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir a venda", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed

        //     JOptionPane.showMessageDialog(this, "Devido a erros, essa função está desabilitada!", "Atenção", JOptionPane.ERROR_MESSAGE);
        habilitarDesabilitarCampos(true);
        alterarSalvar = "alterar";
        int linha = jtVendas.getSelectedRow();
        int codigoVenda = (int) jtVendas.getValueAt(linha, 0);
        listaProdutosVendasProdutosModel = produtosVendasProdutosService.getListaProdutosVendasProdutosDAO(codigoVenda);
        DefaultTableModel modelo = (DefaultTableModel) jtProdutosVendas.getModel();
        modelo.setNumRows(0);
        for (int i = 0; i < listaProdutosVendasProdutosModel.size(); i++) {
            jtfNumeroVenda.setText(String.valueOf(listaProdutosVendasProdutosModel.get(i).getModelVendasProdutos().getVendas()));
            modelo.addRow(new Object[]{
                listaProdutosVendasProdutosModel.get(i).getModelProdutos().getProCodigoProduto(),
                listaProdutosVendasProdutosModel.get(i).getModelProdutos().getProDescricao(),
                listaProdutosVendasProdutosModel.get(i).getModelVendasProdutos().getVenProQuantidade(),
                listaProdutosVendasProdutosModel.get(i).getModelVendasProdutos().getVendasProValor(),
                listaProdutosVendasProdutosModel.get(i).getModelVendasProdutos().getVenProQuantidade()
                * listaProdutosVendasProdutosModel.get(i).getModelVendasProdutos().getVendasProValor()
            });
        }
        somarValorTotalProduto();
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jbAlterarActionPerformed
    /**
     * Preenche o comboBox com todos os clientes
     */
    private void listarClientes() {
        listaClienteModel = clienteService.getListaClienteDAO();
        jcbNomeCliente.removeAllItems();
        int cont = listaClienteModel.size();
        for (int i = 0; i < cont; i++) {
            jcbNomeCliente.addItem(listaClienteModel.get(i).getCliNome());
        }
    }

    /**
     * preencher o comboBox com todos os produtos
     */
    private void listarProdutos() {
        listaProdutoModel = produtoService.getListaProdutoDAO();
        jcbNomeProduto.removeAllItems();
        int cont = listaProdutoModel.size();
        for (int i = 0; i < cont; i++) {
            jcbNomeProduto.addItem(listaProdutoModel.get(i).getProDescricao());
        }

    }

    private void carregarVendas() {
        DefaultTableModel modelo = (DefaultTableModel) jtVendas.getModel();
        listaVendasCliente = vendasClienteService.getListaVendasClienteDAO();
        int cont = listaVendasCliente.size();
        modelo.setNumRows(0);
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaVendasCliente.get(i).getModelVendas().getIdVenda(),
                listaVendasCliente.get(i).getModelCliente().getCliTelefone(),
                listaVendasCliente.get(i).getModelVendas().getVenDataVenda()
            });
        }
    }

    /**
     * Soma todos os produtos da venda
     */
    private void somarValorTotalProduto() {
        double soma = 0, valor;
        int cont = jtProdutosVendas.getRowCount();

        for (int i = 0; i < cont; i++) {
            valor = (double) jtProdutosVendas.getValueAt(i, 4);
            soma = soma + valor;
        }
        jtfValorTotal.setText(String.valueOf(soma));
        aplicarDescontos();
    }

    /**
     * Atribui ao iniciar o frame o código do cliente no jtfCodNome pelo
     * comboBox
     */
    private void preencherCodigoCliente() {
        clienteModel = clienteService.getClienteDAO(jcbNomeCliente.getSelectedItem().toString());
        jtfCodCliente.setText(String.valueOf(clienteModel.getIdCliente()));
    }

    /**
     * Atribui ao iniciar o frame o código do produto no jtfCodProduto pelo
     * comboBox
     */
    private void preencherCodigoProduto() {
        produtoModel = produtoService.retornarProdutoDAO(jcbNomeProduto.getSelectedItem().toString());
        jtfCodProduto.setText(String.valueOf(produtoModel.getProCodigoProduto()));
    }

    /**
     * Limpar formulario de vendas
     */
    private void limparFormulario() {
        jtfQuantidade.setText("");
        jtfNumeroVenda.setText("");
        jtfValorTotal.setText("");
        jtfDesconto.setText("");
        jtfCodCliente.setText("");
        jtfCodProduto.setText("");
        DefaultTableModel modelo = (DefaultTableModel) jtProdutosVendas.getModel();
        modelo.setNumRows(0);
    }

    private void habilitarDesabilitarCampos(boolean condicao) {
        jbSalvar.setEnabled(condicao);
        jcbNomeCliente.setEnabled(condicao);
        jcbNomeProduto.setEnabled(condicao);
        jtfNumeroVenda.setEnabled(condicao);
        jcbNomeCliente.setEnabled(condicao);
        jtfQuantidade.setEnabled(condicao);
        jbAdicionar.setEnabled(condicao);
        jbRemoverProdutos.setEnabled(condicao);
        jtfDesconto.setEnabled(condicao);
        jtfValorTotal.setEnabled(condicao);
        jbCancelar.setEnabled(condicao);
    }

    /**
     * Aplica descontos ao valor final de venda
     */
    private void aplicarDescontos() {
        try {
            jtfValorTotal.setText(String.valueOf(
                    Double.parseDouble(jtfValorTotal.getText()) - Double.parseDouble(jtfDesconto.getText())));
        } catch (NumberFormatException e) {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbRemoverProdutos;
    private javax.swing.JButton jbSalvar;
    private componentes.UJComboBox jcbNomeCliente;
    private componentes.UJComboBox jcbNomeProduto;
    private javax.swing.JTable jtProdutosVendas;
    private javax.swing.JTable jtVendas;
    private javax.swing.JTextField jtfCodCliente;
    private javax.swing.JTextField jtfCodProduto;
    private javax.swing.JTextField jtfDesconto;
    private javax.swing.JTextField jtfNumeroVenda;
    private javax.swing.JTextField jtfPesquisa;
    private javax.swing.JTextField jtfQuantidade;
    private javax.swing.JTextField jtfValorTotal;
    // End of variables declaration//GEN-END:variables
}
